// @Architecture(descriptionShort="English Case 5 waiting-room epilogue dialogue", type="data", icon="layers")
/**
 * Case 5 epilogue EN — courthouse waiting room (spec §19.3).
 */

import type { DialogueLine } from '../../../types/index.js';

const WAITING_ROOM = 'assets/bg_waiting_room.webp';

export const CASE5_EPILOGUE_EN: DialogueLine[] = [
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'December 9, 8:10 PM. Courthouse waiting room.', bgm: 'epilogue' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Mr. Ramon. I have to tell you something and I will not enjoy saying it.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Say it, Mr. Barriga.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'The four thousand two hundred fifty pesos are evidence in a criminal file.', pose: 'barriga_sorpresa' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'The court asked for them this afternoon and I had to hand them over.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'I had recorded the payment, but those bills were used to incriminate you and are now in the court\'s custody. That the tribunal keeps them as evidence does not by itself void the receipt.', pose: 'barriga_sorpresa' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Mr. Barriga: I do not want that murderer to have paid my rent. Can we withdraw the credit from our accounts and let the court decide what to do with the money?', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'If you ask me, yes. I will note we withdrew the credit by mutual agreement; I will keep the copy and proof of the correction.', pose: 'barriga_aliviado' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'I ask.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: '...Then you owe me seventeen months again.', pose: 'barriga_reclamo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Eighteen on Saturday.', pose: 'barriga_reclamo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'But that is not fair! The murderer paid that money!', pose: 'chapulin_panic' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'That is exactly why, young man. Because the murderer paid it.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Let it go, Chapulin.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'It is the first rent in my life I am glad to owe again.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Down the hall walks the Sergeant with a sheet in his hand and his cap crooked.', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'Counselor! Counselors!', pose: 'pazguato_saludo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'I got promoted! First officer!', pose: 'pazguato_decidido' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Congratulations, Sergeant!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'They will not call me Sergeant anymore.', pose: 'pazguato_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'And I have been Sergeant for twenty-six years.', pose: 'pazguato_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Then keep being Sergeant, man. Nobody listens to the paperwork anyway.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: '...At your service, Counselor.', pose: 'pazguato_saludo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'From the other end of the hall comes Super Sam, briefcase in one hand and hand-crank calculator under his arm.', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Counselor.', pose: 'supersam_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Mr. Prosecutor.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Not anymore. They suspended me this afternoon. Six months and probably forever.', pose: 'supersam_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'I am sorry.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Do not be. It came cheap.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'A man I left eighteen days in a drawer paid the difference.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Mr. Prosecutor... and the bag?', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'I left it in the courtroom. The clerk cleared the table and took it out to this waiting room.', pose: 'supersam_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'I remember on my own now.', pose: 'supersam_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'The prosecutor keeps walking. He does not say "time is money."', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Don Ramon, your badge.', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Keep it a while longer, young man. I do not deserve it that much today.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'But you did nothing wrong!', pose: 'chapulin_panic' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'No, young man. But I did not see it either.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'That man told me Saturday, at four fifty-six in the afternoon, that they had sold the door to my own house.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'And I thought he was talking pretty.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Don Ramon stares down the hall a while.' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'He had two watches, young man. One on each arm.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'And both told the right time.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Do not get down, Don Ramon. It is over.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Besides, look on the bright side: they paid your rent.', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'And took it back the same day.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Well there you go! Do not look a gift horse... time flies when you are having fun!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: '......', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Chapulin, nobody gave me a horse.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'They gave me seventeen months, and time flew before I had any fun.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Exactly! That is why I said it!', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Chanfle!', pose: 'donramon_shock' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'The two start walking toward the courthouse door.' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Don Ramon, what will you do now?', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Look for work, young man. Like every Monday of my life.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'And if someone needs a lawyer again?', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Let them shout.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'There is always someone shouting "who will defend me now?"', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'And off I go!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Late.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'But I am going.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'But you go.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'They leave. On the bench where the clerk set items cleared from the courtroom sits an empty canvas bag nobody picks up.' }
];
