// @Architecture(descriptionShort="Case 5 waiting-room epilogue dialogue", type="data", icon="layers")
/**
 * Case 5 epilogue — Sala de espera del tribunal (spec §19.3).
 */

import type { DialogueLine } from '../../../types/index.js';

const WAITING_ROOM = 'assets/bg_waiting_room.webp';

export const CASE5_EPILOGUE: DialogueLine[] = [
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: '9 de diciembre, 20:10. Sala de espera del tribunal.', bgm: 'epilogue' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Señor Ramón. Tengo que decirle una cosa y no me va a gustar decirla.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Dígala, señor Barriga.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Los cuatro mil doscientos cincuenta pesos son prueba en un expediente penal.', pose: 'barriga_sorpresa' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Me los pidió el juzgado esta tarde y se los tuve que dar.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Yo había asentado el pago, pero esos billetes se usaron para incriminarlo y ahora están a disposición del juzgado. Que el tribunal los conserve como prueba no anula por sí solo el recibo.', pose: 'barriga_sorpresa' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Señor Barriga: no quiero que ese asesino haya pagado mi renta. ¿Podemos retirar el abono de nuestras cuentas y dejar que el juzgado resuelva qué hacer con el dinero?', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Si usted me lo pide, sí. Haré constar que retiramos el abono por acuerdo de los dos; conservaré la copia y la constancia de la rectificación.', pose: 'barriga_aliviado' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Se lo pido.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: '...Entonces vuelve a deberme diecisiete meses.', pose: 'barriga_reclamo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Dieciocho el sábado.', pose: 'barriga_reclamo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Pero eso no es justo! ¡Ese dinero lo pagó el asesino!', pose: 'chapulin_panic' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'BARRIGA', text: 'Por eso mismo, joven. Porque lo pagó el asesino.', pose: 'barriga_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Déjelo, Chapulín.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Es la primera renta de mi vida que me da gusto volver a deber.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Por el pasillo cruza el Sargento con una hoja en la mano y la gorra torcida.', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: '¡Mi Licenciado! ¡Mis licenciados!', pose: 'pazguato_saludo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: '¡Me ascendieron! ¡Primer oficial!', pose: 'pazguato_decidido' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Felicidades, Sargento!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'Es que ya no me van a decir Sargento.', pose: 'pazguato_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: 'Y llevo veintiséis años siendo Sargento.', pose: 'pazguato_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Pues siga siendo Sargento, hombre. Al fin que nadie le hace caso a los papeles.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SARGENTO', text: '...A sus órdenes, mi Licenciado.', pose: 'pazguato_saludo' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Por el otro extremo del pasillo sale Super Sam, con el portafolios en una mano y la calculadora de manivela bajo el brazo.', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Counselor.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Señor fiscal.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Ya no. Me suspendieron esta tarde. Seis meses y probablemente para siempre.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Lo siento.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'No lo sienta. Me salió barato.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Un hombre al que dejé dieciocho días en un cajón pagó la diferencia.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Señor fiscal... ¿y la bolsa?', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'La dejé en la sala de audiencias. El secretario despejó la mesa y la sacó a esta sala de espera.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'SUPER SAM', text: 'Ya me acuerdo solo.', pose: 'supersam_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'El fiscal sigue de largo. No dice «time is money».', sfx: 'whoosh' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Don Ramón, su insignia.', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Quédesela un rato más, joven. Yo hoy no la merezco tanto.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Pero si usted no hizo nada malo!', pose: 'chapulin_panic' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'No, joven. Pero tampoco lo vi.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Ese señor me dijo el sábado, a las cuatro cincuenta y seis de la tarde, que me habían vendido la puerta de mi propia casa.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Y yo pensé que estaba hablando bonito.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Don Ramón se queda mirando el pasillo un rato.' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Tenía dos relojes, joven. Uno en cada brazo.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Y los dos daban la hora bien.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'No se me achicopale, Don Ramón. Ya quedó.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Además, míreselo por el lado bueno: le pagaron la renta.', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Y me la quitaron el mismo día.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Pues ahí está! ¡A caballo regalado... más vale ciento volando!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: '......', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Chapulín, a mí no me regalaron ningún caballo.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Me regalaron diecisiete meses y se me fueron volando los ciento.', pose: 'donramon_sweat' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Exactamente! ¡Por eso lo dije!', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: '¡Chanfle!', pose: 'donramon_shock' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Los dos empiezan a caminar hacia la puerta del tribunal.' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Don Ramón, ¿y ahora qué va a hacer?', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Pues buscar trabajo, joven. Como todos los lunes de mi vida.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¿Y si alguien vuelve a necesitar un abogado?', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Pues que grite.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Aquí siempre hay alguien gritando «¿y ahora quién podrá defenderme?».', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: '¡Y ahí voy yo!', pose: 'chapulin_point' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Tarde.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DEFENSA', text: 'Pero voy.', pose: 'chapulin_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'DON RAMÓN', text: 'Pero va.', pose: 'donramon_idle' },
  { bg: WAITING_ROOM, furniture: 'none', speaker: 'NARRADOR', text: 'Salen. Sobre el banco donde el secretario dejó los objetos retirados de la sala de audiencias queda una bolsa de lona floja, sin su algodón, que nadie recoge.' }
];
