// @Architecture(descriptionShort="Case 5 day-4 opening present, T9 contradiction successes, GIRO 4", type="data", icon="layers")
/**
 * Case 5 Trial Day 4 — opening present, T9 successes, GIRO 4 (spec §17).
 */

import type { DialogueLine } from '../../../types/index.js';

export const CASE5_DAY4_OPENING_PRESENT_SUCCESS: DialogueLine[] = [
  { speaker: 'DEFENSA', text: '¡La bitácora de mantenimiento del Archivo, señor juez, y la tira del termógrafo del pasillo siete!', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'DEFENSA', text: 'El tres de diciembre reventó un tubo en el muro del pasillo siete. Pusieron la caldera y dos secadores al máximo y los dejaron cuatro días.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'El termógrafo del edificio, que lleva dieciocho años registrando datos en tiras cambiadas cada domingo, anotó treinta y un grados sostenidos en la del cuatro de diciembre.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Y el legista calculó la hora de la muerte con la tabla de una sala a veinte.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: '¡Cáspita! ¿Y eso qué significa?', pose: 'judge_shock' },
  { speaker: 'NARRADOR', text: 'Un cuerpo pierde calor hacia el aire que lo rodea. Cuanto más frío el aire, más rápido se enfría.' },
  { speaker: 'NARRADOR', text: 'La curva de abajo es la que usó el perito: una sala a veinte grados.' },
  { speaker: 'NARRADOR', text: 'La curva de arriba es la del pasillo 7 esa tarde: treinta y un grados. El cuerpo se enfrió mucho más despacio.' },
  { speaker: 'NARRADOR', text: 'A la misma temperatura medida a las 18:40, la curva de arriba pone la muerte veinticinco minutos antes.' },
  { speaker: 'NARRADOR', text: 'El legista se pone de pie en la segunda fila de la galería, sin que nadie lo llame.', bg: 'assets/bg_courtroom.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'Habla durante cuarenta segundos con el secretario, hace dos cuentas en un papel y asiente con la cabeza.', sfx: 'realization' },
  { speaker: 'SECRETARIO', text: 'Señor juez, el perito rectifica su dictamen. Con treinta y un grados, el intervalo se corrige.' },
  { speaker: 'JUEZ', text: 'Dígalo.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'SECRETARIO', text: 'De las dieciséis treinta y cinco a las diecisiete cero cinco.', updateEvidence: 'informe_forense_c5' },
  { speaker: 'NARRADOR', text: 'Rumor bajo en la galería, que tarda en crecer porque la sala tarda en entenderlo.', bgm: 'suspense' },
  { speaker: 'SECRETARIO', text: '...Señor juez. Con la venia.' },
  { speaker: 'SECRETARIO', text: 'El acusado firmó su entrada a las dieciséis cuarenta y su salida a las dieciséis cincuenta y ocho.' },
  { speaker: 'SECRETARIO', text: 'La representación social hace notar que la defensa acaba de meter a su propio cliente dentro de la ventana.' },
  { speaker: 'NARRADOR', text: 'La galería estalla. El Juez golpea el mazo cinco veces.', sfx: 'gavel' },
  { speaker: 'JUEZ', text: '¡ORDEN! ¡ORDEN EN LA SALA!', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: '¡Licenciado Chapulín! ¿Usted sabe lo que acaba de hacer?', pose: 'judge_shock' },
  { speaker: 'DEFENSA', text: 'Lo sé, señor juez. Lo supe a las cinco cuarenta de la mañana.', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: '¡Acaba usted de colocar a su defendido a solas con la víctima dentro de la hora de la muerte!', pose: 'judge_shock', updateProfile: 'perfil_donramon' },
  { speaker: 'DEFENSA', text: 'Sí, señor juez.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Y acabo de demostrar que la hora registrada tampoco descarta al otro hombre. Todavía tengo que probar que llegó al pasillo.', pose: 'chapulin_point' },
  { speaker: 'NARRADOR', text: 'Silencio.', bgm: 'suspense' },
  { speaker: 'JUEZ', text: '...Explíquese.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'El licenciado Berrondo entregó su gafete a las dieciséis cincuenta.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'La fiscalía la trató como hora de salida hasta que impugnamos el encabezado el martes.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Antes, las dieciséis cincuenta quedaban fuera de la ventana del perito.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'Ahora entran en ella. Y como el libro no acredita salida, tampoco excluye que siguiera allí a las diecisiete cero dos.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'BERRONDO', text: '......', pose: 'berrondo_idle' },
  { speaker: 'DON RAMÓN', text: '(Ahí está, joven.)', pose: 'donramon_idle' },
  { speaker: 'DON RAMÓN', text: '(Ahí está el detalle.)', pose: 'donramon_idle' },
  { speaker: 'JUEZ', text: 'La corte entiende. Y la corte advierte a la defensa que a partir de este momento juega sin red.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: 'Si usted no coloca a alguien más dentro de ese pasillo, el único que queda colocado es su cliente.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'Lo sé, señor juez.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'La defensa llama a la encargada de la ventanilla de peritos del Archivo Judicial.', pose: 'chapulin_point' },
  { speaker: 'JUEZ', text: 'Nombre y ocupación.', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'Genoveva Peñaloza Suárez. Encargada de la ventanilla de peritos y auxiliares de la justicia. Trece años.', pose: 'genoveva_idle' },
  { speaker: 'GENOVEVA', text: 'Y quiero hacer constar que vengo citada.', pose: 'genoveva_reglamento' },
  { speaker: 'JUEZ', text: 'Todo el mundo viene citado, señorita. Declare usted.', sfx: 'gavel', pose: 'judge_gavel' }
];

export const CASE5_D4_T1_LIBRO_SUCCESS: DialogueLine[] = [
  { cutin: 'objection_protesto', speaker: 'DEFENSA', text: '¡PROTESTO!', sfx: 'desk_slam', bgm: 'objection', pose: 'chapulin_slam' },
  { speaker: 'DEFENSA', text: 'Señorita Peñaloza, con todo respeto: su libro no tiene columna de salida.', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...Sí la tiene.', pose: 'genoveva_idle' },
  { speaker: 'DEFENSA', text: 'Léale a la corte el encabezado impreso de la segunda columna.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'GENOVEVA', text: '...«Hora de devolución de gafete».', pose: 'genoveva_sweat' },
  { speaker: 'NARRADOR', text: 'Silencio en la sala.', sfx: 'realization' },
  { speaker: 'GENOVEVA', text: '......', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Trece años.', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Trece años diciéndole «hora de salida» a una columna que dice otra cosa.', pose: 'genoveva_sweat' },
  { speaker: 'DEFENSA', text: 'Todo el mundo le dice así, señorita. Yo también confundí los términos hasta que leí el encabezado el martes.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Señor juez: ese libro no registra quién estaba dentro del Archivo.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'Registra quién pidió un gafete y quién lo devolvió.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: 'Que se asiente con esas palabras exactas.', sfx: 'gavel', pose: 'judge_gavel', updateProfile: 'perfil_genoveva' },
  { speaker: 'DEFENSA', text: 'Y una cosa más, señorita, porque usted es la única persona de este juicio que se sabe el reglamento.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Un síndico que ya devolvió el gafete, ¿puede seguir dentro del edificio?', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...Sí, señor.', pose: 'genoveva_sweat' },
  { speaker: 'GENOVEVA', text: 'Con su credencial puede estar en el depósito de bienes a cualquier hora, todas las horas que quiera, y nadie tiene por qué saberlo.', pose: 'genoveva_reglamento' },
  { speaker: 'GENOVEVA', text: 'Es lo que dice el papel.', pose: 'genoveva_idle' },
  { speaker: 'NARRADOR', text: 'Rumor creciente en la galería.', sfx: 'realization', bgm: 'objection' },
  { speaker: 'BERRONDO', text: 'Señor juez, con la venia: eso es exacto y yo mismo lo declaré ayer.', pose: 'berrondo_idle' },
  { speaker: 'BERRONDO', text: 'No he ocultado nunca ninguna de esas dos cosas, porque las dos son perfectamente legales.', pose: 'berrondo_sweat' },
  { speaker: 'DEFENSA', text: '(Está sudando. Desde ayer está sudando.)', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: 'Defensa: estar en un sótano no es estar en un pasillo.', pose: 'judge_neutral' },
  { speaker: 'JUEZ', text: 'Esta corte lleva cuatro días esperando que alguien suba una escalera.', pose: 'judge_thinking' },
  { speaker: 'DEFENSA', text: '(Ya voy, señor juez. Nada más una cosa antes.)', pose: 'chapulin_idle' }
];

export const CASE5_D4_T1_CEDULARIO_SUCCESS: DialogueLine[] = [
  { cutin: 'objection_toma_eso', speaker: 'DEFENSA', text: '¡TOMA ESO!', sfx: 'desk_slam', pose: 'chapulin_slam' },
  { speaker: 'DEFENSA', text: 'El cedulario del huacal nueve tiene nueve cajones, señor juez. Y cada cajón tiene un rótulo.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'Y los rótulos no son nombres. Son calles.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: '«Aguascalientes a Bucareli.» «Bucareli a Donceles.» «Donceles a Espanto.»', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Señorita Peñaloza: si alguien abrió un cajón, su vale dice qué calles.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'GENOVEVA', text: '...Con su rótulo exacto, señor. Es el reglamento.', pose: 'genoveva_idle' },
  { speaker: 'JUEZ', text: 'Señorita, ¿trae usted esos vales?', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'Traigo los del año, señor juez. Vienen citados.', pose: 'genoveva_reglamento' },
  { speaker: 'NARRADOR', text: 'La testigo saca de una carpeta de hule un fajo de papeletas rosas atadas con una liga.', bgm: 'suspense' },
  { speaker: 'JUEZ', text: 'El del veintinueve de noviembre.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'GENOVEVA', text: '...Hay uno, señor juez.', pose: 'genoveva_sweat' },
  { speaker: 'GENOVEVA', text: '«Veintinueve de noviembre. Huacal nueve. Cedulario. Solicitante: licenciado Fulgencio Berrondo. Firma: F. Berrondo.»', pose: 'genoveva_idle' },
  { speaker: 'GENOVEVA', text: '«Cajón: Donceles a Espanto.»', pose: 'genoveva_shock' },
  { speaker: 'NARRADOR', text: 'La galería entera se vuelve hacia la mesa de la fiscalía.', sfx: 'realization', bgm: 'pursuit' },
  { speaker: 'DEFENSA', text: '¡Y fíjese en la fecha, señor juez! El veintinueve de noviembre fue lunes.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: '¡Y el licenciado Berrondo declaró el martes que baja al huacal dos veces al mes — sólo los jueves!', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'BERRONDO', text: '......', pose: 'berrondo_sweat' },
  { speaker: 'DON RAMÓN', text: '...Señor juez.', pose: 'donramon_shock' },
  { speaker: 'DON RAMÓN', text: 'Yo vivo en la calle del Espanto número ocho.', pose: 'donramon_idle' },
  { speaker: 'DON RAMÓN', text: 'Y en la mano de ese muerto había una esquina de tarjeta que dice mi calle.', pose: 'donramon_shock' },
  { speaker: 'NARRADOR', text: 'El Juez se pone de pie.', sfx: 'gavel' },
  { speaker: 'JUEZ', text: '¡ORDEN!', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'SECRETARIO', text: 'Recibo la carpeta, señor juez.' },
  { speaker: 'JUEZ', text: 'La testigo queda a disposición de esta corte. Su carpeta de vales, en resguardo del tribunal.', pose: 'judge_neutral' },
  { speaker: 'JUEZ', text: 'Licenciado Chapulín.', pose: 'judge_thinking' },
  { speaker: 'JUEZ', text: 'Esta corte lleva cuatro días prohibiéndole a usted señalar a una persona, y hoy se lo va a ordenar.', sfx: 'gavel', pose: 'judge_gavel' }
];
