// @Architecture(descriptionShort="Case 5 day-4 opening present, T9 contradiction successes, GIRO 4, English", type="data", icon="layers")
/**
 * Case 5 Trial Day 4 — opening present, T9 successes, GIRO 4 (spec §17), English.
 */

import type { DialogueLine } from '../../../types/index.js';

export const CASE5_DAY4_OPENING_PRESENT_SUCCESS_EN: DialogueLine[] = [
  { speaker: 'DEFENSA', text: 'The Archive maintenance log, Your Honor, and the thermograph strip from corridor seven!', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'DEFENSA', text: 'On December third a pipe burst in corridor seven\'s wall. They ran the boiler and two dryers at maximum and left them for four days.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'The building thermograph, which has recorded data on strips changed every Sunday for eighteen years, logged sustained thirty-one degrees on December fourth\'s strip.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'And the medical examiner calculated time of death using a table for a room at twenty.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: 'Good grief! And what does that mean?', pose: 'judge_shock' },
  { speaker: 'NARRADOR', text: 'A body loses heat to the air around it. The colder the air, the faster it cools.' },
  { speaker: 'NARRADOR', text: 'The lower curve is the one the expert used: a room at twenty degrees.' },
  { speaker: 'NARRADOR', text: 'The upper curve is corridor 7 that afternoon: thirty-one degrees. The body cooled much more slowly.' },
  { speaker: 'NARRADOR', text: 'At the same temperature measured at 6:40 PM, the upper curve places death twenty-five minutes earlier.' },
  { speaker: 'NARRADOR', text: 'The medical examiner stands up in the second row of the gallery without being called.', bg: 'assets/bg_courtroom.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'He speaks with the clerk for forty seconds, does two sums on a slip of paper, and nods.', sfx: 'realization' },
  { speaker: 'SECRETARIO', text: 'Your Honor, the expert corrects his report. At thirty-one degrees, the interval is adjusted.' },
  { speaker: 'JUEZ', text: 'State it.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'SECRETARIO', text: 'From 4:35 PM to 5:05 PM.', updateEvidence: 'informe_forense_c5' },
  { speaker: 'NARRADOR', text: 'A low murmur in the gallery, slow to grow because the room is slow to understand it.', bgm: 'suspense' },
  { speaker: 'SECRETARIO', text: '...Your Honor. With permission.' },
  { speaker: 'SECRETARIO', text: 'The defendant signed his entry at 4:40 PM and his exit at 4:58 PM.' },
  { speaker: 'SECRETARIO', text: 'The prosecution notes that the defense has just placed its own client inside the window.' },
  { speaker: 'NARRADOR', text: 'The gallery erupts.', sfx: 'gavel' },
  { speaker: 'JUEZ', text: 'ORDER! ORDER IN THE COURT!', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: 'Counselor Chapulin! Do you know what you have just done?', pose: 'judge_shock' },
  { speaker: 'DEFENSA', text: 'I do, Your Honor. I knew at five forty this morning.', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: 'You have just placed your client alone with the victim within the hour of death!', pose: 'judge_shock', updateProfile: 'perfil_donramon' },
  { speaker: 'DEFENSA', text: 'Yes, Your Honor.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'And I have just shown that the logged hour does not rule out the other man either. I still have to prove he reached the corridor.', pose: 'chapulin_point' },
  { speaker: 'NARRADOR', text: 'Silence.', bgm: 'suspense' },
  { speaker: 'JUEZ', text: '...Explain yourself.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'Counselor Berrondo returned his visitor badge at 4:50 PM.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'The prosecution treated that as a time of departure until we challenged the column header on Tuesday.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Before that, 4:50 PM fell outside the expert\'s window.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'Now it falls inside it. And because the log does not prove departure, it does not rule out that he was still there at 5:02 PM.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'BERRONDO', text: '......', pose: 'berrondo_idle' },
  { speaker: 'DON RAMÓN', text: '(There it is, kid.)', pose: 'donramon_idle' },
  { speaker: 'DON RAMÓN', text: '(There\'s the detail.)', pose: 'donramon_idle' },
  { speaker: 'JUEZ', text: 'The court understands. And the court warns the defense that from this moment it plays without a net.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: 'If you do not place someone else inside that corridor, the only person left placed there is your client.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'I know, Your Honor.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'The defense calls the clerk in charge of the Judicial Archive experts\' window.', pose: 'chapulin_point' },
  { speaker: 'JUEZ', text: 'Name and occupation.', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'Genoveva Penaloza Suarez. Clerk in charge of the experts and court auxiliaries window. Thirteen years.', pose: 'genoveva_idle' },
  { speaker: 'GENOVEVA', text: 'And I wish to note that I was summoned.', pose: 'genoveva_reglamento' },
  { speaker: 'JUEZ', text: 'Everyone here was summoned, miss. Take the stand.', sfx: 'gavel', pose: 'judge_gavel' }
];

export const CASE5_D4_T1_LIBRO_SUCCESS_EN: DialogueLine[] = [
  { cutin: 'objection_protesto', speaker: 'DEFENSA', text: 'OBJECTION!', sfx: 'desk_slam', bgm: 'objection', pose: 'chapulin_slam' },
  { speaker: 'DEFENSA', text: 'Miss Penaloza, with all respect: your log has no departure column.', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...It does.', pose: 'genoveva_idle' },
  { speaker: 'DEFENSA', text: 'Read the court the printed header of the second column.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'GENOVEVA', text: '..."Time badge returned".', pose: 'genoveva_sweat' },
  { speaker: 'NARRADOR', text: 'Silence in the courtroom.', sfx: 'realization' },
  { speaker: 'GENOVEVA', text: '......', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Thirteen years.', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Thirteen years calling a column that says something else "time of departure".', pose: 'genoveva_sweat' },
  { speaker: 'DEFENSA', text: 'Everyone calls it that, miss. I confused the terms too until I read the header on Tuesday.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Your Honor: that log does not record who was inside the Archive.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'It records who requested a badge and who returned it.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: 'Let that be entered in those exact words.', sfx: 'gavel', pose: 'judge_gavel', updateProfile: 'perfil_genoveva' },
  { speaker: 'DEFENSA', text: 'And one more thing, miss, because you are the only person in this trial who knows the regulations.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'A syndic who has already returned his badge — can he remain inside the building?', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...Yes, sir.', pose: 'genoveva_sweat' },
  { speaker: 'GENOVEVA', text: 'With his credential he may be in the goods deposit at any hour, for as many hours as he wishes, and nobody has to know.', pose: 'genoveva_reglamento' },
  { speaker: 'GENOVEVA', text: 'That is what the paper says.', pose: 'genoveva_idle' },
  { speaker: 'NARRADOR', text: 'Rising murmur in the gallery.', sfx: 'realization', bgm: 'objection' },
  { speaker: 'BERRONDO', text: 'Your Honor, with permission: that is exact, and I said so myself yesterday.', pose: 'berrondo_idle' },
  { speaker: 'BERRONDO', text: 'I have never hidden either of those things, because both are perfectly legal.', pose: 'berrondo_sweat' },
  { speaker: 'DEFENSA', text: '(He is sweating. He has been sweating since yesterday.)', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: 'Defense: being in a basement is not being in a corridor.', pose: 'judge_neutral' },
  { speaker: 'JUEZ', text: 'This court has spent four days waiting for someone to climb a staircase.', pose: 'judge_thinking' },
  { speaker: 'DEFENSA', text: '(I am coming, Your Honor. Just one thing first.)', pose: 'chapulin_idle' }
];

export const CASE5_D4_T1_CEDULARIO_SUCCESS_EN: DialogueLine[] = [
  { cutin: 'objection_toma_eso', speaker: 'DEFENSA', text: 'TAKE THAT!', sfx: 'desk_slam', pose: 'chapulin_slam' },
  { speaker: 'DEFENSA', text: 'The card-file index in crate nine has nine drawers, Your Honor. And each drawer has a label.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'And the labels are not names. They are streets.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: '"Aguascalientes to Bucareli." "Bucareli to Donceles." "Donceles to Espanto."', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Miss Penaloza: if someone opened a drawer, the voucher says which streets.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'GENOVEVA', text: '...With its exact label, sir. That is the regulation.', pose: 'genoveva_idle' },
  { speaker: 'JUEZ', text: 'Miss, do you have those vouchers with you?', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'I have this year\'s, Your Honor. They were summoned.', pose: 'genoveva_reglamento' },
  { speaker: 'NARRADOR', text: 'The witness pulls from a rubber folder a bundle of pink slips tied with a rubber band.', bgm: 'suspense' },
  { speaker: 'JUEZ', text: 'The one from November twenty-ninth.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'GENOVEVA', text: '...There is one, Your Honor.', pose: 'genoveva_sweat' },
  { speaker: 'GENOVEVA', text: '"November 29. Crate 9. Card-file index. Requester: Counselor Fulgencio Berrondo. Signature: F. Berrondo."', pose: 'genoveva_idle' },
  { speaker: 'GENOVEVA', text: '"Drawer: Donceles to Espanto."', pose: 'genoveva_shock' },
  { speaker: 'NARRADOR', text: 'The entire gallery turns toward the prosecution table.', sfx: 'realization', bgm: 'pursuit' },
  { speaker: 'DEFENSA', text: 'And look at the date, Your Honor! November twenty-ninth was a Monday.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'And Counselor Berrondo testified on Tuesday that he goes down to the crate twice a month — only on Thursdays!', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'BERRONDO', text: '......', pose: 'berrondo_sweat' },
  { speaker: 'DON RAMÓN', text: '...Your Honor.', pose: 'donramon_shock' },
  { speaker: 'DON RAMÓN', text: 'I live on Calle del Espanto number eight.', pose: 'donramon_idle' },
  { speaker: 'DON RAMÓN', text: 'And in that dead man\'s hand was a corner of a card that names my street.', pose: 'donramon_shock' },
  { speaker: 'NARRADOR', text: 'The Judge stands.', sfx: 'gavel' },
  { speaker: 'JUEZ', text: 'ORDER!', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'SECRETARIO', text: 'I receive the folder, Your Honor.' },
  { speaker: 'JUEZ', text: 'The witness remains at this court\'s disposal. Her voucher folder, in the tribunal\'s custody.', pose: 'judge_neutral' },
  { speaker: 'JUEZ', text: 'Counselor Chapulin.', pose: 'judge_thinking' },
  { speaker: 'JUEZ', text: 'This court has spent four days forbidding you to point at a person, and today it is going to order you to.', sfx: 'gavel', pose: 'judge_gavel' }
];
