// @Architecture(descriptionShort="Case 5 day-4 opening present, T9 contradiction successes, GIRO 4, English", type="data", icon="layers")
/**
 * Case 5 Trial Day 4 — opening present, T9 successes, GIRO 4 (spec §17), English.
 */

import type { DialogueLine } from '../../../types/index.js';

export const CASE5_DAY4_OPENING_PRESENT_SUCCESS_EN: DialogueLine[] = [
  { speaker: 'DEFENSA', text: 'The Archive maintenance log, Your Honor, and the thermograph strip from corridor seven!', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'DEFENSA', text: 'On December third a pipe burst in corridor seven\'s wall. They ran the boiler and two dryers at maximum and left them for four days.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'The building thermograph, which has recorded data on strips changed every Sunday for eighteen years, logged sustained thirty-one degrees on December fourth\'s strip.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'And the medical examiner calculated time of death using a table for a room at twenty.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: 'Good grief! And what does that mean?', pose: 'judge_shock' },
  { speaker: 'DEFENSA', text: 'You see, Your Honor: a body throws its heat at the air, like throwing money out the window... no, wait, that one is not it either.', bg: 'assets/examine_termografo.webp', furniture: 'none' },
  { speaker: 'DEFENSA', text: 'The point is: the colder the air, the faster the deceased... the body, cools down. Well, that is the idea.', bg: 'assets/examine_termografo.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'The lower curve is the one the expert used: a room at twenty degrees.', bg: 'assets/plate_curva_enfriamiento.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'The upper curve is corridor 7 that afternoon: thirty-one degrees. The body cooled much more slowly.', bg: 'assets/plate_curva_enfriamiento.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'At the same temperature measured at 6:40 PM, the upper curve places death twenty-five minutes earlier.', bg: 'assets/plate_curva_enfriamiento.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'The medical examiner stands up in the second row of the gallery without being called.', bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none' },
  { speaker: 'NARRADOR', text: 'He speaks with the clerk for forty seconds, does two sums on a slip of paper, and nods.', sfx: 'realization' },
  { speaker: 'SECRETARIO', text: 'Your Honor, the expert corrects his report. At thirty-one degrees, the interval is adjusted.' },
  { speaker: 'JUEZ', text: 'State it.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'SECRETARIO', text: 'From 4:35 PM to 5:05 PM.', updateEvidence: 'informe_forense_c5' },
  { bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none', speaker: 'NARRADOR', text: 'A low murmur in the gallery, slow to grow because the room is slow to understand it.', bgm: 'suspense' },
  { speaker: 'SECRETARIO', text: '...Your Honor. With permission.' },
  { speaker: 'SECRETARIO', text: 'The defendant signed his entry at 4:40 PM and his exit at 4:58 PM.' },
  { speaker: 'SECRETARIO', text: 'The prosecution notes that the defense has just placed its own client inside the window.' },
  { bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none', speaker: 'NARRADOR', text: 'The gallery erupts.', sfx: 'gavel' },
  { speaker: 'JUEZ', text: 'ORDER! ORDER IN THE COURT!', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: 'Counselor Chapulin! Do you know what you have just done?', pose: 'judge_shock' },
  { speaker: 'DEFENSA', text: 'I do, Your Honor. I knew at five forty this morning.', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: 'You have just placed your client alone with the victim within the hour of death!', pose: 'judge_shock' },
  { speaker: 'DEFENSA', text: 'Yes, Your Honor.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'And I have just shown that the logged hour does not rule out the other man either. I still have to prove he reached the corridor.', pose: 'chapulin_point' },
  { bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none', speaker: 'NARRADOR', text: 'Silence.', bgm: 'suspense' },
  { speaker: 'JUEZ', text: '...Explain yourself.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'Counselor Berrondo returned his visitor badge at 4:50 PM.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'The prosecution treated that as a time of departure until we challenged the column header on Tuesday.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Before that, 4:50 PM fell outside the expert\'s window.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'Now it falls inside it. And because the log does not prove departure, it does not rule out that he was still there at 5:02 PM.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'BERRONDO', text: '......', pose: 'berrondo_idle', bg: 'assets/bg_courtroom.webp' },
  { speaker: 'DON RAMÓN', text: '(There it is, kid.)', pose: 'donramon_idle' },
  { speaker: 'DON RAMÓN', text: '(There\'s the detail.)', pose: 'donramon_idle' },
  { speaker: 'JUEZ', text: 'The court understands. And the court warns the defense that from this moment it plays without a net.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'JUEZ', text: 'If you do not place someone else inside that corridor, the only person left placed there is your client.', pose: 'judge_neutral' },
  { speaker: 'DEFENSA', text: 'I know, Your Honor.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'The defense calls the clerk in charge of the Judicial Archive experts\' window.', pose: 'chapulin_point' },
  { speaker: 'JUEZ', text: 'Name and occupation.', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'Genoveva Penaloza Suarez. Clerk in charge of the experts and court auxiliaries window. Thirteen years.', pose: 'genoveva_idle' },
  { speaker: 'GENOVEVA', text: 'And I wish to note that I was summoned.', pose: 'genoveva_reglamento' },
  { speaker: 'JUEZ', text: 'Everyone here was summoned, miss. Take the stand.', sfx: 'gavel', pose: 'judge_gavel' }
];

export const CASE5_D4_T1_LIBRO_SUCCESS_EN: DialogueLine[] = [
  { cutin: 'objection_protesto', speaker: 'DEFENSA', text: 'OBJECTION!', sfx: 'desk_slam', bgm: 'objection', pose: 'chapulin_slam' },
  { speaker: 'DEFENSA', text: 'Miss Penaloza, with all respect: your log has no departure column.', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...It does.', pose: 'genoveva_idle' },
  { speaker: 'DEFENSA', text: 'Read the court the printed header of the second column.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'GENOVEVA', text: '..."Time badge returned".', pose: 'genoveva_sweat' },
  { bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none', speaker: 'NARRADOR', text: 'Silence in the courtroom.', sfx: 'realization' },
  { speaker: 'GENOVEVA', text: '......', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Thirteen years.', pose: 'genoveva_shock' },
  { speaker: 'GENOVEVA', text: 'Thirteen years calling a column that says something else "time of departure".', pose: 'genoveva_sweat' },
  { speaker: 'DEFENSA', text: 'Everyone calls it that, miss. I confused the terms too until I read the header on Tuesday.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'Your Honor: that log does not record who was inside the Archive.', pose: 'chapulin_point' },
  { speaker: 'DEFENSA', text: 'It records who requested a badge and who returned it.', pose: 'chapulin_slam', sfx: 'desk_slam' },
  { speaker: 'JUEZ', text: 'Let that be entered in those exact words.', sfx: 'gavel', pose: 'judge_gavel' },
  { speaker: 'DEFENSA', text: 'And one more thing, miss, because you are the only person in this trial who knows the regulations.', pose: 'chapulin_idle' },
  { speaker: 'DEFENSA', text: 'A syndic who has already returned his badge — can he remain inside the building?', pose: 'chapulin_point' },
  { speaker: 'GENOVEVA', text: '...Yes, sir.', pose: 'genoveva_sweat' },
  { speaker: 'GENOVEVA', text: 'With his credential he may be in the goods deposit at any hour, for as many hours as he wishes, and nobody has to know.', pose: 'genoveva_reglamento' },
  { speaker: 'GENOVEVA', text: 'That is what the paper says.', pose: 'genoveva_idle' },
  { bg: 'assets/bg_gallery_case5_secretary_berrondo_accused.webp', furniture: 'none', speaker: 'NARRADOR', text: 'Rising murmur in the gallery.', sfx: 'realization', bgm: 'objection' },
  { speaker: 'BERRONDO', text: 'Your Honor, with permission: that is exact, and I said so myself yesterday.', pose: 'berrondo_idle', bg: 'assets/bg_courtroom.webp' },
  { speaker: 'BERRONDO', text: 'I have never hidden either of those things, because both are perfectly legal.', pose: 'berrondo_sweat', bg: 'assets/bg_courtroom.webp' },
  { speaker: 'DEFENSA', text: '(He is sweating. He has been sweating since yesterday.)', pose: 'chapulin_idle' },
  { speaker: 'JUEZ', text: 'Defense: being in a basement is not being in a corridor.', pose: 'judge_neutral' },
  { speaker: 'JUEZ', text: 'This court has spent four days waiting for someone to climb a staircase.', pose: 'judge_thinking' },
  { speaker: 'JUEZ', text: 'Ms. Penaloza, take a seat and remain available to the court.', pose: 'judge_neutral' },
  { speaker: 'GENOVEVA', text: 'Yes, Your Honor.', pose: 'genoveva_idle' },
  { speaker: 'DEFENSA', text: '(He was in the building. We still need to know what he prepared before coming.)', pose: 'chapulin_idle' }
];

export const CASE5_D4_T1_CEDULARIO_SUCCESS_EN: DialogueLine[] = [
      { speaker: 'DEFENSA', text: 'Your Honor, I ask that Ms. Penaloza return to the stand. She files the deposit vouchers.', pose: 'chapulin_point' },
      { speaker: 'JUEZ', text: 'Miss, check your folder. Is there a card-file consultation by Counselor Berrondo on November twenty-ninth?', pose: 'judge_neutral' },
      { speaker: 'NARRADOR', text: 'Genoveva opens a rubber folder and separates the pink slips tied with a rubber band.', bgm: 'suspense' },
      { speaker: 'GENOVEVA', text: 'Yes, Your Honor. "November twenty-ninth. Crate 9. Item consulted: card-file index. Requester: Counselor Fulgencio Berrondo. Signature: F. Berrondo."', pose: 'genoveva_sweat' },
      { speaker: 'DEFENSA', text: 'That was a Monday. The voucher records a consultation, but not which card he saw, and it was not required to open the crate.', pose: 'chapulin_slam', sfx: 'desk_slam' },
      { speaker: 'DEFENSA', text: 'Counselor, you testified that you only visit the crate on Thursdays.', pose: 'chapulin_point' },
      { speaker: 'BERRONDO', text: 'The voucher records an extraordinary consultation. It does not say which card I saw, and my office permits me to consult that item.', pose: 'berrondo_idle', bg: 'assets/bg_courtroom.webp' },
      { speaker: 'JUEZ', text: 'Let that be entered. The card will be identified by its address, not by this voucher.', pose: 'judge_neutral' },
      { speaker: 'SECRETARIO', text: 'I receive the folder, Your Honor.' },
      { speaker: 'JUEZ', text: 'It remains in the court\'s custody. Ms. Penaloza, remain available to this court.', pose: 'judge_neutral' },
      { speaker: 'JUEZ', text: 'Counselor Chapulin. This court has spent four days forbidding you to point at a person, and today it is going to order you to.', sfx: 'gavel', pose: 'judge_gavel' }
];
